# Generated by Django 4.2.6 on 2024-01-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='endereco_bairro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='endereco_cidade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='endereco_estado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='endereco_estado_sigla',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='endereco_numero',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='endereco_rua',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
    ]
