# Generated by Django 4.2.6 on 2024-01-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_alter_anuncio_imagens_alter_anuncio_opcionais'),
        ('vendedores', '0002_alter_vendedor_endereco_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='anuncios',
            field=models.ManyToManyField(blank=True, related_name='anuncios', to='anuncios.anuncio'),
        ),
    ]
