# Generated by Django 4.2.6 on 2024-01-25 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=1500)),
                ('ano', models.PositiveIntegerField()),
                ('quilometragem', models.PositiveIntegerField()),
                ('valor', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CorVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionalVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.marcaveiculo')),
            ],
        ),
        migrations.AddField(
            model_name='marcaveiculo',
            name='modelos',
            field=models.ManyToManyField(related_name='modelos', to='anuncios.modeloveiculo'),
        ),
        migrations.CreateModel(
            name='ImagemAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('caminho', models.CharField(max_length=200)),
                ('imagem', models.ImageField(upload_to='anuncios')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.anuncio')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='cor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anuncios.corveiculo'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='imagens',
            field=models.ManyToManyField(related_name='imagens', to='anuncios.imagemanuncio'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anuncios.marcaveiculo'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anuncios.modeloveiculo'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='opcionais',
            field=models.ManyToManyField(to='anuncios.opcionalveiculo'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedores.vendedor'),
        ),
    ]
