# Generated by Django 4.2.6 on 2024-01-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcaveiculo',
            name='modelos',
            field=models.ManyToManyField(blank=True, related_name='modelos', to='anuncios.modeloveiculo'),
        ),
    ]
