# Generated by Django 4.2.6 on 2024-01-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_alter_marcaveiculo_modelos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagens',
            field=models.ManyToManyField(blank=True, related_name='imagens', to='anuncios.imagemanuncio'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='opcionais',
            field=models.ManyToManyField(blank=True, to='anuncios.opcionalveiculo'),
        ),
    ]
