# Generated by Django 4.2.6 on 2024-01-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_tipoveiculo_anuncio_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='tipo',
        ),
        migrations.AddField(
            model_name='modeloveiculo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anuncios.tipoveiculo'),
        ),
    ]
