# Generated by Django 5.0.1 on 2024-01-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_remove_anuncio_tipo_modeloveiculo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemanuncio',
            name='caminho',
        ),
    ]
